version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    # command: >
    #   "ollama serve & sleep 5 && ollama run deepseek-r1 && wait"
    command: >
      "ollama serve"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-api
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - LLM_SERVER=http://ollama:11434
      - USER_AGENT=docs-ai-agent/1.0
    volumes:
      - ./chroma_db:/app/chroma_db

volumes:
  ollama_models:
